### PR TITLE
Midi port system improvements

### PR DESCRIPTION
**Pull request by agraef**
(As sketched out in https://github.com/plugdata-team/plugdata/pull/991#issuecomment-1659778286.) This is a first stab at improving the new system of MIDI ports which recently landed in the develop branch (which already is a big improvement, but it can be made better). Specifically, instead of presenting the user with unwieldy lists of *all* available MIDI input and output ports, it uses separate curated lists which only have the ports that the user actually enabled in the MIDI settings, making it much easier to deal with port selection on a system with lots of attached MIDI devices.

The present PR already goes a long way towards providing something that's similar to vanilla Pd's MIDI port system. It should be clean and flexible enough for future extensions and working towards that goal, but also provides a more workable and user-friendly solution to keep users happy for the time being.

Only tested on Linux so far.

### CODE REVIEW

**Comment by agraef** [comment]
Here's a little screencast showing the changes in action:

Peek 2023-08-03 01-28

**Comment by agraef** [comment]
Yeah, I have lots of MIDI devices (the mioXM alone already has 16 MIDI ins and outs), which provided the motivation for this PR. :)

Here's what my MIDI setup dialog in plugdata typically looks like:

Peek 2023-08-03 01-32

**Comment by agraef** [comment]
It goes without saying that with such an amount of MIDI ports (most of which will always be disabled), the current method of just listing all MIDI ports as Pd ports simply isn't workable, not even for testing purposes. I'm sure that there are plugdata users out there which have similar amounts of MIDI gear. Come on, you know who you are. :) They will thank you if you merge this PR.

**Comment by agraef** [comment]
Another advantage of this PR is that after startup, patches which output MIDI to the default port (i.e., on MIDI channels 1 to 16), as many patches do, will output to the internal GM synth by default. Thus, once the internal GM synth is enabled in the MIDI settings, such patches will just work without any further ado.

**Comment by alcomposer** [comment]
> Here's a little screencast showing the changes in action:
> 
> Peek 2023-08-03 01-28

We may want to have the midi device/channel selector in the inspector as well?

**Comment by agraef** [comment]
> We may want to have the midi device/channel selector in the inspector as well?

This isn't an object property. The popup menu (which is only active in run, not in edit mode) just gives you a shortcut to set the MIDI channel argument of various MIDI objects. (At least that's my understanding. Tim wrote that part, this PR only piggybacks on that to make the menus tidier.)

**Comment by agraef** [comment]
Tested on Windows now, seems to work there, too. (I do get crashes with [virtual MIDI ports](https://www.tobias-erichsen.de/software/loopmidi.html) on Windows, but these seem to be unrelated to this PR, since the latest builds from the develop branch exhibit the same misbehavior. For all I know, this might be a JUCE issue, but I haven't looked into it yet.)

I will test on Mac (M1) next. I need to build the app myself there, as the Mac CI build fails on my fork.

**Comment by agraef** [comment]
While I'm at it, I might just as well fix a little regression I noticed in the new MIDI ports implementation, namely that it doesn't update the MIDI device list when the settings are invoked (I'm pretty sure that this worked with the old MIDI implementation). Fixed in https://github.com/plugdata-team/plugdata/pull/1009/commits/3c85f6ba45583a48b1194bdd2a8f4c00f52ae210.

**Comment by timothyschoen** [comment]
Very nice, thanks for looking at this! The macOS CI build will indeed fail on forks, because it will also sign/notarise the build with my secret keys.

**Comment by agraef** [comment]
> The macOS CI build will indeed fail on forks, because it will also sign/notarise the build with my secret keys.

Yes, I know. I assume that it won't just take any self-generated keys to replace those, so that I can at least make the build work on my fork?

**Comment by agraef** [comment]
Anyway, thanks for merging! I think that the standalone MIDI system should be in pretty good shape now, I just need to think about how to fix #1004, then I should be able to use the standalone in my upcoming courses in the winter term.

**Comment by timothyschoen** [comment]
> > The macOS CI build will indeed fail on forks, because it will also sign/notarise the build with my secret keys.
> 
> Yes, I know. I assume that it won't just take any self-generated keys to replace those, so that I can at least make the build work on my fork?

If you're in the (paid) Apple Development Program, you could add your account details as Github Actions secrets. If you have an account I can guide you through setting it up, it is a bit of a hassle. I think a better idea would be to have a check in my Github workflow file that disables the signing/notarising if the secret keys are empty. That does mean macOS will complain when you try to run it, but it's better than having the build fail.


> Anyway, thanks for merging! I think that the standalone MIDI system should be in pretty good shape now, I just need to think about how to fix #1004, then I should be able to use the standalone in my upcoming courses in the winter term.

I can take care of #1004 today, we can look at how AudioDeviceManager does it and take inspiration from that. When do the courses start? If possible, I can try to get this release finished off before that time.

**Comment by agraef** [comment]
> If you're in the (paid) Apple Development Program

Nope.

> I think a better idea would be to have a check in my Github workflow file that disables the signing/notarising if the secret keys are empty.

Good idea. For the time being, I could just skip the signing on my testing branch. But it would be better to have that change upstream in both main and develop so that it doesn't slip into my PRs.

> I can take care of https://github.com/plugdata-team/plugdata/issues/1004 today, we can look at how AudioDeviceManager does it and take inspiration from that.

Yep, that was my plan, too. But of course I wouldn't mind if you beat me to it. :)

> When do the courses start? If possible, I can try to get this release finished off before that time.

That would be much appreciated. There's still ample time, our winter term starts in the 2nd half of October.

**Comment by timothyschoen** [comment]
> That would be much appreciated. There's still ample time, our winter term starts in the 2nd half of October.

Perfect, I think I can get something stable out by that time. The biggest thing holding it back right now, is that I want to update to pd-0.54 so we can get those nice multi-channel connections.

I like how you solved the port indexing by just applying a sorting algorithm, that makes it very flexible!

**Pull request merged**
