### PR TITLE
Alternative for saving extra data inside DAW session file 

### PR DESCRIPTION
**Pull request by jyg**
Hi, 
following this discussion https://github.com/plugdata-team/plugdata/pull/648
Here is a proposal for saving extra data from a patch (for example, array content, lists, text) inside the session-data of a DAW.
I included a patch for testing in the folder Resources/Patches : storing_extra_data_in_daw.pd

The way that data are stored through XmlElements structure is certainly not the most efficient.

We should discuss about the name of the sender and receiver objects in the patch : [r load] and [s databuffer]. May be we may choose more explicit names ?

### CODE REVIEW

**Comment by timothyschoen** [comment]
Nice! I'll merge this soon, I want to replace the XmlElements here with JUCE ValueTree, which can also export XML but is easier to use

**Comment by jyg** [comment]
Great ! 
Anyway, XmlElements is not so robust in this usecase. For example, if you send a list to [r databuffer] with the first element containing some special characters (like  /  ), the DAW session data are lost, and if you restart it, even the patch is not loaded anymore.
I think this is because Xml tags cannot contain any forbidden characters, like /, #, %, etc..., and in the code I'm using the first list element as tag name.

**Comment by timothyschoen** [comment]
Actually, XmlElement looks fine in the context. We need to add it to another XmlElement anyway

**Comment by jyg** [comment]
Fine ! 
We just have to be aware that sending a list to `[databuffer]` with the first element containing forbidden characters ( / " < > ( ) etc...) may corrupt plugin-data in DAW session.

**Comment by timothyschoen** [comment]
We could apply base64 encoding to the name to prevent this

**Comment by jyg** [comment]
yes, but "/" (everywhere) and "-" (in first position) are still forbidden in Xml tag name.
Maybe base64url, but we must prepend a arbitrary character to prevent having "-" in first position.
Anyway, that would be much better than checking the name in [daw_storage] abstraction.

**Pull request merged**
