### PR TITLE
Virtual MIDI input must be activated (fixes #986)

### LINKED ISSUE #986: ALSA MIDI input and/output on Linux (standalone)
There should be dedicated ALSA MIDI ports to get MIDI into and out of plugdata. I see that plugdata standalone does expose ALSA sequencer ports "from plugdata" (for capture) and "to plugdata" (for playback) which I guess are intended for this purpose. But in plugdata's MIDI settings they are listed incorrectly: "from plugdata" is listed as an input, and "to plugdata" as an output port. I'd say that this should be the other way round, i.e., plugdata should read from the "to plugdata", and write to the "from plugdata" port.

Otherwise, I don't see what the purpose of these ports should be -- create instant MIDI feedback? ;-) (Because that's in fact what happens if I enable "to plugdata" with a patch that takes, say, note input and creates any note output.) But if I leave "to plugdata" disabled in the MIDI settings then sending MIDI to that port from another application just seems to be ignored.

### PR DESCRIPTION
**Pull request by agraef**
Fix for "to plugdata" port not working, as discussed in #986.

### CODE REVIEW

**Comment by timothyschoen** [comment]
I'm not completely sure about this: I think the MIDI device should be created on startup, but only enabled after you enable to toggle switch in settings? Normally, the start() method would get called here, inside setMidiInputDeviceEnabled: https://github.com/plugdata-team/plugdata/blob/b68b29e4e7e7a11b22584816487af5904d7262a1/Source/Dialogs/MIDISettingsPanel.h#L30

Unless you're suggesting that we enable plugdata's own input and output by default, which would be fine with me, just checking.

**Comment by agraef** [comment]
Hmm, you're right, the way it is now, the input side of to plugdata is just always enabled, which might not be what we want. Or maybe we do, since the same is the case with the "from plugdata" output, which also has its processing thread enabled during startup (see PluginProcessor.cpp:185) and consequently is always on.

Maybe both "to plugdata" and "from plugdata" should just be entirely invisible to the plugdata user? (In the setup dialog, as well as the new noteout popup menu item that you added recently.) If they're meant to be used by other apps to send and receive MIDI data to/from plugdata, that makes a lot of sense to me. And having them visible to the end user is bound to cause a lot of confusion.

OTOH, being able to enable and disable these ports also has its use cases. But for that to work, we'd need to move both calls (startBackgroundThread() in PluginProcessor.cpp:185, and start() in PlugDataWindow.h:434) to the setup dialog callbacks. Let me give that a try.

(BTW, you already merged this commit with #994 which came straight from my testing branch. But I can send you a followup PR to correct this.)

**Comment by agraef** [comment]
This stuff in the MIDI setup just isn't working at all. It just won't send any MIDI at all, no matter what output I enable. Did you make any recent changes to this which broke it? I could swear that this worked before.

**Comment by agraef** [comment]
Looks like you did, rev. 913785ec4b7c70a6720ff79dd5371091ecb05131 and 6e27300a43330fdf5d83cbed377d85a389960510. I'll try whether reverting these makes MIDI output work again.

**Comment by timothyschoen** [comment]
> Looks like you did, rev. [913785e](https://github.com/plugdata-team/plugdata/commit/913785ec4b7c70a6720ff79dd5371091ecb05131) and [6e27300](https://github.com/plugdata-team/plugdata/commit/6e27300a43330fdf5d83cbed377d85a389960510). I'll try whether reverting these makes MIDI output work again.

I think I see what's wrong. The order of the ports in the right-click list don't match with the order of MIDI output devices. And also, the default option should be that it sends MIDI to all ports. I should be able to fix that today.

**Comment by timothyschoen** [comment]
> > Looks like you did, rev. [913785e](https://github.com/plugdata-team/plugdata/commit/913785ec4b7c70a6720ff79dd5371091ecb05131) and [6e27300](https://github.com/plugdata-team/plugdata/commit/6e27300a43330fdf5d83cbed377d85a389960510). I'll try whether reverting these makes MIDI output work again.
> 
> I think I see what's wrong. The order of the ports in the right-click list doesn't match with the order of MIDI output devices. And also, the default option should be that it sends MIDI to all ports. I should be able to fix that today.

Tested in pd-vanilla, apparently sending to all devices is not the default option, as I thought. So it's just the device order problem

**Comment by timothyschoen** [comment]
Working on a fix: 6e0017efbf4f99b6202865c9f87a5f30f1487ed7

This seems to work better on Mac, since everything pulls the order or MIDI object from the same place. We can also swap plugdata's own input/output ports at the source this way, and the MIDI code is not as scattered all over the place.

**Comment by agraef** [comment]
gdb backtrace for setup:

~~~
Thread 1 "plugdata" received signal SIGSEGV, Segmentation fault.
0x0000555555ad81f0 in juce::String::String(juce::String const&) ()
(gdb) bt
#0  0x0000555555ad81f0 in juce::String::String(juce::String const&) ()
#1  0x0000555555dd8ce6 in MidiSettingsToggle::MidiSettingsToggle(bool, PluginProcessor*, juce::MidiDeviceInfo&, juce::AudioDeviceManager&) ()
#2  0x0000555555de80a8 in StandaloneMIDISettings::updateDevices() ()
#3  0x0000555555e0e385 in SettingsDialog::SettingsDialog(PluginEditor*) ()
#4  0x0000555555db7080 in Dialogs::showSettingsDialog(PluginEditor*) ()
#5  0x0000555555db71ec in std::_Function_handler<void (int), Dialogs::showMainMenu(PluginEditor*, juce::Component*)::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int&&) ()
#6  0x0000555555dbfb6a in std::_Function_handler<void (int), ArrowPopupMenu::showMenuAsync(juce::PopupMenu*, juce::PopupMenu::Options const&, std::function<void (int)> const&)::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int&&) ()
#7  0x000055555595e25e in juce::ModalCallbackFunction::create<std::function<void (int)>&>(std::function<void (int)>&)::Callable::modalStateFinished(int) ()
#8  0x000055555589ac76 in juce::ModalComponentManager::handleAsyncUpdate() ()
#9  0x0000555555acb512 in std::_Function_handler<void (int), juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int&&) ()
#10 0x0000555555abdafe in std::_Function_handler<void (), juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#11 0x0000555555ac8288 in juce::MessageManager::runDispatchLoop() ()
#12 0x00005555556d0a69 in juce::JUCEApplicationBase::main() ()
--Type <RET> for more, q to quit, c to continue without paging--
#13 0x00007ffff7540850 in __libc_start_call_main (
    main=main@entry=0x5555556c16a0 <main>, argc=argc@entry=1, 
    argv=argv@entry=0x7fffffffdcb8)
    at ../sysdeps/nptl/libc_start_call_main.h:58
#14 0x00007ffff754090a in __libc_start_main_impl (main=0x5555556c16a0 <main>, 
    argc=1, argv=0x7fffffffdcb8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffdca8)
    at ../csu/libc-start.c:360
#15 0x000055555578e835 in _start ()
~~~

gdb backtrace for right-click on noteout:

~~~
Thread 1 "plugdata" received signal SIGSEGV, Segmentation fault.
0x0000555555ad81f0 in juce::String::String(juce::String const&) ()
(gdb) bt
#0  0x0000555555ad81f0 in juce::String::String(juce::String const&) ()
#1  0x0000555555ea1ce6 in MidiObject::mouseUp(juce::MouseEvent const&) ()
#2  0x000055555593b582 in juce::Component::internalMouseUp(juce::MouseInputSource, juce::PointerState const&, juce::Time, juce::ModifierKeys) ()
#3  0x00005555559b6025 in juce::MouseInputSourceInternal::setButtons(juce::PointerState const&, juce::Time, juce::ModifierKeys) ()
#4  0x000055555593ce67 in juce::MouseInputSource::handleEvent(juce::ComponentPeer&, juce::Point<float>, long long, juce::ModifierKeys, float, float, juce::PenDetails const&) ()
#5  0x000055555593d8ec in juce::XWindowSystem::handleButtonReleaseEvent(juce::LinuxComponentPeer*, XButtonEvent const&) const ()
#6  0x000055555593e375 in juce::XWindowSystem::handleWindowMessage(juce::LinuxComponentPeer*, _XEvent&) const ()
#7  0x000055555593e77e in std::_Function_handler<void (int), juce::XWindowSystem::initialiseXDisplay()::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int&&) ()
#8  0x0000555555abdafe in std::_Function_handler<void (), juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#9  0x0000555555ac8288 in juce::MessageManager::runDispatchLoop() ()
#10 0x00005555556d0a69 in juce::JUCEApplicationBase::main() ()
#11 0x00007ffff7540850 in ?? () from /usr/lib/libc.so.6
#12 0x00007ffff754090a in __libc_start_main () from /usr/lib/libc.so.6
--Type <RET> for more, q to quit, c to continue without paging--
#13 0x000055555578e835 in _start ()
~~~

**Comment by agraef** [comment]
For the time being, I can get back to a working state by getting rid of all your recent MIDI-related changes. But I hope that you can fix these segfaults, then I'll be happy to test again.

**Comment by agraef** [comment]
Well, looking at the code in rev. https://github.com/plugdata-team/plugdata/commit/6e0017efbf4f99b6202865c9f87a5f30f1487ed7, I think that the input flags for the 'from plugdata' and 'to plugdata' toggles in the `new MidiSettingsToggle()` calls are the wrong way round again. I tried fixing that. The setup dialog still crashes, but apparently in a slightly different place:

~~~
Thread 1 "plugdata" received signal SIGSEGV, Segmentation fault.
0x0000555555ad81f0 in juce::String::String(juce::String const&) ()
(gdb) bt
#0  0x0000555555ad81f0 in juce::String::String(juce::String const&) ()
#1  0x0000555555de7d2e in StandaloneMIDISettings::updateDevices() ()
#2  0x0000555555e0e385 in SettingsDialog::SettingsDialog(PluginEditor*) ()
#3  0x0000555555db7080 in Dialogs::showSettingsDialog(PluginEditor*) ()
~~~

MidiObject::mouseUp() also looks alright to me, at least I don't see anything obvious with crash potential there. And the popup menu seems to work alright with notein, so why does it crash with noteout?

In either case the segfault seems to happen in the juce::String::String(juce::String const&) copy constructor, so I guess that something's wrong with the device identifier strings being passed to midiDeviceManager->isMidiDeviceEnabled(), but they're all being passed by reference, so what's up with that?

Maybe the fact that the notein popup works, while the noteout popup crashes provides a clue? There *is* a difference between input and output in MidiDeviceManager::isMidiDeviceEnabled(), namely that there's this loop `for (auto* midiOut : midiOutputs)` checking for `midiOut->getIdentifier() == identifier` there which might trigger the copy constructor. Is there a reason for that asymmetry between input and output in MidiDeviceManager::isMidiDeviceEnabled()?

**Comment by agraef** [comment]
Hmm, where does the String type being used in MidiDeviceManager.h, setMidiDeviceEnabled() and isMidiDeviceEnabled(), come from anyway? That header file has no includes at all. Maybe it's picking up a wrong String type there? Emacs also flags a number of other types being used there as undeclared. Maybe `juce_audio_utils/juce_audio_utils.h` needs to be included there?

**Comment by agraef** [comment]
FWIW, there's a bit of rather sloppy coding (missing return statements) in isMidiDeviceEnabled and getMidiDeviceIndex. I added those now. However, this doesn't seem to completely cure the crashes either. The code *still* crashes a lot even after all the changes I did.

For the record, here are all the changes that I did so far. Please double-check that I got those right before you commit them.

~~~diff
diff --git a/Source/Dialogs/MIDISettingsPanel.h b/Source/Dialogs/MIDISettingsPanel.h
index b2024fd9..3d081653 100644
--- a/Source/Dialogs/MIDISettingsPanel.h
+++ b/Source/Dialogs/MIDISettingsPanel.h
@@ -91,7 +91,7 @@ private:
             // The internal plugdata ports should be viewed from our perspective instead of that of an external application
             if(deviceInfo.name == "to plugdata")
             {
-                midiInputProperties.add(new MidiSettingsToggle(false, processor, deviceInfo, deviceManager));
+                midiInputProperties.add(new MidiSettingsToggle(true, processor, deviceInfo, deviceManager));
                 continue;
             }
             
@@ -102,7 +102,7 @@ private:
         for (auto& deviceInfo : midiOutputDevices) {
             if(deviceInfo.name == "from plugdata")
             {
-                midiOutputProperties.add(new MidiSettingsToggle(true, processor, deviceInfo, deviceManager));
+                midiOutputProperties.add(new MidiSettingsToggle(false, processor, deviceInfo, deviceManager));
                 continue;
             }
             
diff --git a/Source/Utility/MidiDeviceManager.h b/Source/Utility/MidiDeviceManager.h
index 80c3f9fc..8a3ea4d9 100644
--- a/Source/Utility/MidiDeviceManager.h
+++ b/Source/Utility/MidiDeviceManager.h
@@ -5,6 +5,7 @@
  */
 
 #pragma once
+#include <juce_audio_utils/juce_audio_utils.h>
 
 // Helper function to encode regular MIDI events into a sysex event
 // The reason we do this, is that we want to append extra information to the MIDI event when it comes in from pd or the device, but JUCE won't allow this
@@ -171,6 +172,7 @@ struct MidiDeviceManager : public ChangeListener
                     return true;
                 }
             }
+            return false;
         }
     }
     
@@ -202,6 +204,7 @@ struct MidiDeviceManager : public ChangeListener
                 return i;
             }
         }
+        return 0;
     }
     
     MidiInput* toPlugdata;
~~~

**Comment by agraef** [comment]
Frankly, I think that the old MIDI code worked much better. While it doesn't give you a way to distinguish different MIDI input and output devices, it's also straightforward and much easier to use. And if you really need that kind of routing functionality, then you can just run plugdata as a plugin in a DAW which gives you all the MIDI routing capabilities that you could ever want. Therefore I think that emulating vanilla's MIDI system in plugdata isn't really necessary.

And your new implementation isn't even a proper emulation of vanilla anyway. You'd really have to go to some lengths to get that kind of system. In vanilla you have a number of slots for MIDI inputs and outputs, and you can choose which slot should be assigned to which MIDI device. Then you can at least predict the channel numbers that will be associated with each device, on both input and output. In your implementation, those channel numbers will be changing all the time, as you unplug existing and plug in new MIDI devices.

**Comment by timothyschoen** [comment]
I agree, those commits needed more attention. Unfortunately clang lets me compile code with missing return statements, it's pretty annoying, I should find a flag to disable that.

The current method is not great indeed, but I think that moving to assignable ports from here should be simple, all we need for that is already there. Since we now have a single place where the order of MIDI ports is decided (the lastMidiInputs/lastMidiOutputs variable in MidiDeviceManager), we just need to set the order up correctly there, and it should all work. But we can also revert to the old way, I'll think about it, it was a lot simpler for sure. But not being able to decide where your MIDI goes is a bit limiting, especially when we have an internal GM synth to play with.

I didn't notice the crashes, but I've mostly tested it on macOS of far, so that's probably why. The develop branch is  unstable right now, this is the last version before a long feature freeze, so we're currently sprinting to get the last features in, we're nearly done with that, but the release is still a while away. After v0.8.0, we're just gonna clean up and fix bugs until v1.0.

**Comment by timothyschoen** [comment]
> FWIW, there's a bit of rather sloppy coding (missing return statements) in isMidiDeviceEnabled and getMidiDeviceIndex. I added those now. However, this doesn't seem to completely cure the crashes either. The code _still_ crashes a lot even after all the changes I did.
> 
> For the record, here are all the changes that I did so far. Please double-check that I got those right before you commit them.
> 
> ```diff
> diff --git a/Source/Dialogs/MIDISettingsPanel.h b/Source/Dialogs/MIDISettingsPanel.h
> index b2024fd9..3d081653 100644
> --- a/Source/Dialogs/MIDISettingsPanel.h
> +++ b/Source/Dialogs/MIDISettingsPanel.h
> @@ -91,7 +91,7 @@ private:
>              // The internal plugdata ports should be viewed from our perspective instead of that of an external application
>              if(deviceInfo.name == "to plugdata")
>              {
> -                midiInputProperties.add(new MidiSettingsToggle(false, processor, deviceInfo, deviceManager));
> +                midiInputProperties.add(new MidiSettingsToggle(true, processor, deviceInfo, deviceManager));
>                  continue;
>              }
>              
> @@ -102,7 +102,7 @@ private:
>          for (auto& deviceInfo : midiOutputDevices) {
>              if(deviceInfo.name == "from plugdata")
>              {
> -                midiOutputProperties.add(new MidiSettingsToggle(true, processor, deviceInfo, deviceManager));
> +                midiOutputProperties.add(new MidiSettingsToggle(false, processor, deviceInfo, deviceManager));
>                  continue;
>              }
>              
> diff --git a/Source/Utility/MidiDeviceManager.h b/Source/Utility/MidiDeviceManager.h
> index 80c3f9fc..8a3ea4d9 100644
> --- a/Source/Utility/MidiDeviceManager.h
> +++ b/Source/Utility/MidiDeviceManager.h
> @@ -5,6 +5,7 @@
>   */
>  
>  #pragma once
> +#include <juce_audio_utils/juce_audio_utils.h>
>  
>  // Helper function to encode regular MIDI events into a sysex event
>  // The reason we do this, is that we want to append extra information to the MIDI event when it comes in from pd or the device, but JUCE won't allow this
> @@ -171,6 +172,7 @@ struct MidiDeviceManager : public ChangeListener
>                      return true;
>                  }
>              }
> +            return false;
>          }
>      }
>      
> @@ -202,6 +204,7 @@ struct MidiDeviceManager : public ChangeListener
>                  return i;
>              }
>          }
> +        return 0;
>      }
>      
>      MidiInput* toPlugdata;
> ```

This is a few essential commits behind, I think I already fixed a few of the issues with 954f06d6a948244d1a527b0581d79a0068ffba14, and a few more after that.

I also fixed the missing include and return statement now.

**Comment by timothyschoen** [comment]
Tested it on Linux now, it seems to work, no crashes yet.

**Pull request closed without merging**
