### PR TITLE
pd-lua 0.11.5 (bugfix release)

### PR DESCRIPTION
**Pull request by agraef**
Update to the latest release, with a critical bugfix.

### CODE REVIEW

**Comment by timothyschoen** [comment]
aaaaa I forgot to submodule update again! I'll fix this one

**Comment by agraef** [comment]
Thanks!

**Comment by agraef** [comment]
Hmm, @timothyschoen, there's something wrong with the sign-on message:

image

That's the version I downloaded from the actions tab. Note that it prints "(lua 5.4)" twice there. That definitely isn't in the version that I built myself from the master branch:

image

That's how it's supposed to look like. So there must be something fishy on the develop branch there, did you change anything with the sign-on message there?

**Comment by agraef** [comment]
git blame in fact reveals that you're to blame. ;-) See https://github.com/plugdata-team/plugdata/commit/0eb1c15b4c4922e645ef80de3a5fde86e107626f. I see what you wanted to do there, but that doesn't work. The precise git revision will *only* be used anyway if you're using a git version of pd-lua, not a tagged release. Which incidentally is also the reason why https://github.com/plugdata-team/plugdata/commit/0eb1c15b4c4922e645ef80de3a5fde86e107626f goes wrong and prints the lua version twice.

Anyway, the proper way to suppress the commit hash there, if that's what you really want to do, is to just disable the PDLUA_VERSION variable in Libraries/CMakeLists.txt:231. If PDLUA_VERSION is not set in the build, it will fall back to the static version data in pdlua.c itself, which will be the current release number without the git revision.

I'll send you a PR in a minute.

**Comment by agraef** [comment]
There you go: #487

**Comment by agraef** [comment]
BTW, if you think about this again and decide that it's useful to have the git revision for git versions of pdlua after all, then all you have to do is to revert https://github.com/plugdata-team/plugdata/commit/0eb1c15b4c4922e645ef80de3a5fde86e107626f.

**Pull request merged**
