### PR TITLE
remove subpatch dot

### PR DESCRIPTION
**Pull request by alcomposer**

### CODE REVIEW

**Comment by dromer** [comment]
What is the suggested alternative to recognize sub-patches/abstractions?

**Comment by alcomposer** [comment]
This was in regard to #1660, up to Tim.

I made this as a PR so we have the option.

**Comment by timothyschoen** [comment]
> abstractions are not intended to be used as widely as subpatches.

More specifically, abstractions are technically a reusable black box, and not really part of your patch. If you use it as intended, you shouldn't have to check what's inside very often. So for subpatches, it was already redundant, and abstractions, you should't have to look inside.

Of course, it's still nice to see if it can be opened on click. The idea is probably to add a hover colour on mouse-over for both subpatches and abstractions. But this is still open for discussion. IMO, it largely accomplishes the same thing without needing something that's constantly visible, and it's easier to understand (hover = clickable) than an dot. This is also a bit similar to what pd-vanilla does, but they do a cursor change, and I think hover colour is easier to understand than a cursor change.

**Comment by timothyschoen** [comment]
https://github.com/plugdata-team/plugdata/assets/44585538/f3b98ce8-f0d6-454e-869d-2fbd4b71b818

**Pull request merged**
