### PR TITLE
Add Perfetto performance debug library

### PR DESCRIPTION
**Pull request by kamomehettapi**
Hi so in debugging issue let me share techinque I think may help other PlugData authors ?

This is Perfetto library developed by Google and was implemented in JUCE library by thirdparty code `melatonin_perfetto`

https://github.com/sudara/melatonin_perfetto

Enable Perfetto flag in cmake and have beautiful data visualization of code running placed on Desktop after program exit

See this blog by author: https://melatonin.dev/blog/using-perfetto-with-juce-for-dsp-and-ui-performance-tuning/

It is useful and realworld I could debug #1966 issue with it, found numerous non obvious performance fixes to speed up menu opening by ~alot%

There is not too much code to add for lib, only downside is Perfetto only operates on functions you trace manually by adding `TRACE_COMPONENT()` calls. So one must add `TRACE_COMPONENT()` everywhere to debug. Those macro are no-op when Perfetto is off

In debugging I added a lot of `TRACE_COMPONENT()` calls. I found I needed lots and lots or I would miss certain events and as was not too familiar with this codebase , I believed it may be good to keep them in ?

Upside is not having to spend hours and hours putting tracing everything you need everytime

Downside is code being littered with `TRACE_COMPONENT()` everywhere ...

But setup for Perfetto is same either way. Switch `ENABLE_PERFETTO` cmake flag and add `TRACE_COMPONENT()` calls to functions want to debug. And note it is usually best to compile `PERFETTO` as well as `Release` config to get more accurate stats Then switch off when building final program.

Can omit all `TRACE_COMPONENT()` stuffs if it's better, I split into own commit

### CODE REVIEW

**Comment by timothyschoen** [comment]
Looks great! Thanks for adding this, I'll take a look at it tomorrow :)

**Comment by alcomposer** [comment]
I've used this module inside plugdata, really useful to find specific issues with JUCE events. Eg functions can easily be triggered via multiple paths, so it's really useful having a simple and elegant log.

However I think we shouldn't populate it inside the code. It gets overwhelming and contradicts the purpose of the library, which is to find specific issues - rather than an overview of the whole app.

**Comment by timothyschoen** [comment]
> I've used this module inside plugdata, really useful to find specific issues with JUCE events. Eg functions can easily be triggered via multiple paths, so it's really useful having a simple and elegant log.
> 
> However I think we shouldn't populate it inside the code. It gets overwhelming and contradicts the purpose of the library, which is to find specific issues - rather than an overview of the whole app.

I'm torn on that tbh. If just by having it in there it would make us discover things that can be optimised, even a few things, wouldn't it already be worth it?

**Comment by alcomposer** [comment]
I think we should add the library. But allow it's use to be dedicated by the debugging process at hand.

Profetto itself mentions it's better to place logging into functions when needed, not lots of functions all over the place.

This is because:

A) it gets bogged down with logging
B) log files become bigger
C) it's harder to see what your profiling with the white noise

**Comment by dromer** [comment]
I'd keep it only in the CMakeLists.txt and the submodule.

This so it can easily be activated when you want to measure something.

The general application to lots/all function calls seems overkill as you only need this during development and when you want to measure something specific.

Of course it would be more effort to apply when you want to do a broad analysis of the whole program again.

**Comment by timothyschoen** [comment]
Great, thanks!!

**Pull request merged**
