### PR TITLE
show in search, and limit `Help` & `Documentation` to when one object is selected

### PR DESCRIPTION
**Pull request by alcomposer**

### CODE REVIEW

**Comment by timothyschoen** [comment]
IMO, this is superseded by 79fc9110c62e876c3bbb2342f82d2f8590c8c452 and 59a66e55e8c97593a1764069432e6ac33ad1a629

**Comment by alcomposer** [comment]
I still think we should have an option to show in search. Please consider this PR.

**Comment by dromer** [comment]
What does "show in search" do?

**Comment by alcomposer** [comment]
"show in search" moves the search panel outliner to that object, and highlights it. So you can see the object on canvas in context with the rest of the objects in the list.

**Comment by dromer** [comment]
Ah, that sounds quite handy.

**Comment by timothyschoen** [comment]
The problem is that there is nothing you can do with the highlighted object in the search panel. So there is not really any reason the user would want to do this.

The point of the search panel is to locate an object. There is currently nothing else you can do from the search panel. So if you already knew where the object was, why would you want to highlight it in the search panel?

I'd rather not pollute the object right-click menu with features that serve no real purpose. It's also preferable not to put actions that are specific to a sidebar panel in the object right-click menu.

**Pull request closed without merging**
