### PR TITLE
Plugin Mode

### PR DESCRIPTION
**Pull request by Nejrup**
- [ ] Still needs to restored properly when stored in DAW session (is this done in 'ImplementationBase' @timothyschoen ?)
- [ ] some weird editor height issue, when editor is restored..

### CODE REVIEW

**Comment by timothyschoen** [comment]
Nice job on this, I'm glad you kept the changes to PluginEditor and PluginProcessor very minimal, so it doesn't interfere with the regular code at all!

Let me know if you feel like this is ready to merge already, or if it's better if I wait.

**Comment by timothyschoen** [comment]
Oh I'll explain the object inplementation system:

There are cases where we need a class that is one-on-one associated to a Pd object, so it can pass it additional input. For example, the [mouse] objects should receive mouse events from JUCE, subpatches need to respond to vis messages, etc.

GUI objects are not suited for this, since they will only be created when they are actually visible (in a canvas or graph, but not in subpatchers for example). Also, there may be 2 guis referring to the same Pd object, if you open a graph in a new tab. The implementation system aims to solve these problems.

**Comment by Nejrup** [comment]
> Oh I'll explain the object inplementation system:
> 
> There are cases where we need a class that is one-on-one associated to a Pd object, so it can pass it additional input. For example, the [mouse] objects should receive mouse events from JUCE, subpatches need to respond to vis messages, etc.
> 
> GUI objects are not suited for this, since they will only be created when they are actually visible (in a canvas or graph, but not in subpatchers for example). Also, there may be 2 guis referring to the same Pd object, if you open a graph in a new tab. The implementation system aims to solve these problems.

Thanks for explaining:)
This is pretty stable now, my issue with ImplementationBase turned out to be a timing issue with Canvas..

Now pluginmode is stored in settings, but it doesn't really make sense unless using standalone only..
Optimally you could store it per patch (but i know that's not possible..)
What would be the best approach to store the setting within a daw session?

**Comment by timothyschoen** [comment]
> > Oh I'll explain the object inplementation system:
> > There are cases where we need a class that is one-on-one associated to a Pd object, so it can pass it additional input. For example, the [mouse] objects should receive mouse events from JUCE, subpatches need to respond to vis messages, etc.
> > GUI objects are not suited for this, since they will only be created when they are actually visible (in a canvas or graph, but not in subpatchers for example). Also, there may be 2 guis referring to the same Pd object, if you open a graph in a new tab. The implementation system aims to solve these problems.
> 
> Thanks for explaining:) This is pretty stable now, my issue with ImplementationBase turned out to be a timing issue with Canvas..
> 
> Now pluginmode is stored in settings, but it doesn't really make sense unless using standalone only.. Optimally you could store it per patch (but i know that's not possible..) What would be the best approach to store the setting within a daw session?

We could store a flag in the DAW preset, you can look at getStateInformation()/setStateInformation(). There is a variable called xmlState there, that's where you'll want to read/write the property from.

**Pull request merged**
