### PR TITLE
pdlua: sync with upstream (doc corrections).

### PR DESCRIPTION
**Pull request by agraef**
Alexandre had some last-minute changes.

Note that the previous update got washed away with your rev. 5a8227dcd541e28ec922c3509fbac0d4d0a700f6, so all these updates are included again as well.

Please remember to update your local main this time. ;-) That is, `git pull` and then `git submodule update --init --recursive`.

### CODE REVIEW

**Comment by agraef** [comment]
pd-lua submodule hash should be c5e2f0683c011f497f98dcfd1b8013e17ef867dc in your working copy afterwards, you can check that with `git submodule status`.

**Comment by agraef** [comment]
Oh, and in the future it would be a good idea to check whether submissions include old submodule hashes unrelated to the PR, because they haven't fully updated their working copy. Happens to the best of us. :)

**Comment by timothyschoen** [comment]
Oh wow, that's dumb of me! I'll try not to mess it up this time

**Comment by agraef** [comment]
:))

**Pull request merged**
