### PR TITLE
Implement patch thumbnails for welcome panel.

### PR DESCRIPTION
**Pull request by alcomposer**
* thumbnail file placed in root dir of patch with same name as PD file: 
if pd file is: `myFile.pd`, then thumbnail file is: `myFile_thumbnail.png`
* Increase size of recent items to 20
* Use rounded scissors for welcome tiles and clip top area with coloured rectangle
* Thumbnail will automatically fill the size of the tile.
* If no thumbnail is present or not png or corrupt, then SVG will be used

image

### CODE REVIEW

**Comment by timothyschoen** [comment]
Nice! I wonder if we should use SVG instead? That way we can ensure it looks good on retina.

**Comment by alcomposer** [comment]
The images are auto scaled. So you can make the image retina size, (realistically they are still drawing very small, so 1024x1024 would be enough).

**Comment by dromer** [comment]
maybe use `_thumb.png` instead? shorter and more direct ;)

**Comment by alcomposer** [comment]
> Nice! I wonder if we should use SVG instead? That way we can ensure it looks good on retina.

We could do both? As vector graphics would be smaller also (depending on the data)

**Comment by alcomposer** [comment]
> maybe use `_thumb.png` instead? shorter and more direct ;)

I'm not sure about using a shorter name. It's quite trivial to change, but `_thumbnail` is clearer? Thoughts?

**Comment by dromer** [comment]
I think `_thumbnail` is too much typing and rather verbose (especially if the patch name is short) and `_thumb` is already clear enough to the majority of users. Maybe could do both? (first one found is used)

Either way there should be clear instructions somewhere that explain this feature, of course.

**Comment by alcomposer** [comment]
Good points. And yes we need the manual for more than just this also!

We need a whole section on how plugin mode works anyway, and how to use it. Including the plugin mode theme, latency compensation, this, and others.

**Pull request merged**
