### PR TITLE
implement simple autosave

### PR DESCRIPTION
**Pull request by alcomposer**

### CODE REVIEW

**Comment by dromer** [comment]
It seems like this _always_ autosaves? Is there a way to disable it? perhaps by setting the interval to 0?

**Comment by alcomposer** [comment]
Yeah, we can easily have a bypass option.

**Comment by dromer** [comment]
@timothyschoen we do really need a way to not force autosave though.

Often enough you are just tweaking around and you wouldn't want plugdata to ruin your saves!

**Comment by timothyschoen** [comment]
Currently, it doesn't autosave to a file anymore. It autosaves to single database file. If you then reopen a file that has a more recent autosaved version, it will ask you if you'd like to recover the autosaved version.

I'm also working on a dialog so you can manually recover if needed:

Screenshot 2023-12-09 at 18 36 16

**Comment by dromer** [comment]
Ooh nice, that's really cool actually.
Perfect, as long as the user doesn't lose any work that they might want to keep.

**Pull request merged**
