### PR TITLE
Add support for Cleveland Music Co. Hothouse as target board

### PR DESCRIPTION
**Pull request by clevelandmusicco**
Submitting at suggestion of .drmr./dreamer on the Electrosmith Discord server. 

2 of 2 PRs

### CODE REVIEW

**Comment by timothyschoen** [comment]
@dromer We have support for this already on the Heavy side? Or will I need to update the toolchain?

**Comment by dromer** [comment]
@timothyschoen see PR on the toolchain

**Comment by timothyschoen** [comment]
I just released the toolchain update. If you get the latest nightly build, you should be able to update the toolchain and use the Hothouse board setup!

**Comment by dromer** [comment]
@timothyschoen you forgot to release tag the toolchain itself. So now develop is broken again :#

**Pull request merged**
