### PR TITLE
Don't use framebuffer for pdlua, as context changes (when using multi…

### PR DESCRIPTION
**Pull request by alcomposer**
…ple editors) will corrupt the graphics context. Use a command cache to replay the last state if it is needed during repaint. WIP

### CODE REVIEW

**Comment by timothyschoen** [comment]
Unfortunately, I think we can't do this, because there is a multi-layer drawing feature coming to pdlua soon that depends on framebuffers

**Comment by alcomposer** [comment]
Yeah, I like the idea of having a pass over FBO objects in the main loop.

However I think we need to keep the `guiCommandBuffeeCache` code so we can update the state of this on its own timer, then use that when rendering into the FBO (at callback rate)

Eg, timer updates cache 60hz
Callback can happen at 170hz

**Comment by alcomposer** [comment]
I have updated this PR to use Framebuffers again, but with them being rendered in the `updateFramebuffers` canvas function.

The framebuffer is registered when a pdlua graphical object is added, and removed when the  SafePointer becomes null.

**Comment by alcomposer** [comment]
Had to move the updateFramebuffer for lua objects to editor, so it will update when canvas is closed.

**Pull request closed without merging**
