### PR TITLE
DOCUMENTATION Overview of Compilation and Compilation Mode 

### PR DESCRIPTION
**Pull request by thouldcroft**
This is an introduction to all of the compilation options with plugdata. 

_**This commit is missing information on flashing to Daisy because I do not have a Daisy to experiment with!!**_

### CODE REVIEW

**Comment by timothyschoen** [comment]
Wow, thanks! I think the "?" button in the compile menu should direct the user to this, since it's easier for the user to correlate with what they see on the screen.

I'll also put this on https://plugdata.org/documentation.html

@dromer, do you have any additions? We should probably explain to Windows users how to install the USB driver manually, in case that fails which it sometimes does.

**Comment by dromer** [comment]
The location of this documentation is odd, since these files are meant for the reference docs.

Further more you have a lot of html syntax embedded into the markdown. It would be better to use pure markdown syntax.

@timothyschoen wait what, you just merged this without looking? o.O

**Comment by timothyschoen** [comment]
I looked, that's all stuff that can be fixed. There is no harm in having this in the repo already, since there is no docs at all right now.

**Comment by dromer** [comment]
This is super messy and I would've liked to have done at least a single reading of this.

**Comment by timothyschoen** [comment]
Also, there's nothing wrong with HTML inside markdown if we're publishing this on the website's docs page. That should just work

**Comment by dromer** [comment]
Sure but it makes it that much harder to read, and any other markdown parser/renderer might completely fail.
It's better to write proper markdown imo and now it's a really odd mix of syntax.

Also referring to image resources that are not local is odd/bad.

I think we should either have a `Docs/` folder in the plugdata repo, or have an entirely separate repository for such docs.
Where are the other docs on the website coming from?

**Comment by dromer** [comment]
Right, here: https://github.com/plugdata-team/plugdata-team.github.io/tree/main/docs

So imo it would be better if this documentation is over there as well.

**Comment by dromer** [comment]
There is some super weird wording in this that I cannot place. Something about an "information registry" and other things that don't make any sense to me.

Sorry @thouldcroft but can you explain what you mean by this? It makes the documentation sound really obscure hard to understand.

**Comment by dromer** [comment]
And sorry but the amount of fluff that is not giving any information is really a lot. If you don't mind I'm going to strip that so we have more clear and direct information.

Right now there are a lot of words that don't communicate anything and I think this will add to confusion rather than clarify what the program is doing or what the intention is.

**Comment by dromer** [comment]
@timothyschoen should I create separate sections as is done for the DAW integration?

**Comment by JoshuaACNewman** [comment]
Hey, @thouldcroft , I'd be happy to send you a Daisy Seed to experiment with!

Really psyched about you taking the initiative on this contribution. Much easier to make something better than to start it from scratch.

**Comment by dromer** [comment]
@thouldcroft thnx for the work to get this started. I've now opened a PR over here: https://github.com/plugdata-team/plugdata-team.github.io/pull/4

**Pull request merged**
